### ISSUE TITLE
Calculaid: Add option to return to open calculator window instead of opening new one

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2.modules#2]
Whenever i use the calculator, i need to switch between some programs and the ONE calculator window...
ctrl-tab works, but needs a number of presses, if i had more than one window active since last using the calc...
To open more than one calc, i would add ctrl-N for as a hotkey while the calculator is active.
Maybe could also be part of Calculaid?

**Comment by ewerybody** [comment]
Interesting idea! Could also be that the CalculAid hotkey just raises the calculator if it's already open?
Or would you rather have 2 different hotkeys for that?

**Comment by sirtet** [comment]
Yes, thats what i meant. Just one hotkey,  as you suggest.

**Comment by ewerybody** [comment]
Hey @sirtet I'm ... 4 years? Whow. I'm deeply sorry this took so long.
Windows actually made it kinda ridiculously hard to solve this. Creating a new Calculator is super easy but the `process_ID` from calling it is for the trash can right away because the calculator will be an `ApplicationFrameWindow` eventually.

What I now did was starting a loop that looks for new windows of this kind discarding the ones that are already there ...
The Bad thing about this is: As the logic is not only based on the class and process name (there can be any kind of `ApplicationFrameWindows`, "Photos" app, or the <kbd>Win+I</kbd> Settings) the window title needs to be taken into consideration. But this is based on **the language** the user has! It works now for English ("Calculator") and German ("Taschenrechner")(I suppose)(didn't test) but any other language solution would need to be hardcoded for this ... 🤦‍♀️

But I have some more thrust on this at the moment :)
Not released yet! But checked into dev.
