### ISSUE TITLE
gtranslate: pasting problems, text to voice, error massages

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2.modules#61]
@Cyberkabauter contributed a couple gtranslate issues in [a2#250](https://github.com/ewerybody/a2/issues/250):

> In MS Word: Selecting the translated entry doesn’t replace the hightlighted source text. Sometime it pastes my clipboard content instead, whatever content it is. In Google Chrome it worked as expected.

Oh dang! Yeah pasting things via clipboard was already a constant issue in early ac'tivAid times ☹ I have [yet another mitigation](https://github.com/ewerybody/a2/blob/254c86292f019ae3a3fe963bde35a95bdf052c26/lib/Autohotkey/lib/clipboard.ahk#L53) in dev yet unreleased. We could have apps acting up like these blacklisted to fallback to `Send` contents or maybe do send things rather by default as the issue turns up over again. (I had this on the DetailsPopup too). Well texts with gtranslate won't ever be thaaat big. So sending should be fine. You know some apps hog in on input and Send might take quite a while "typing" the text for you thats why pasting is so attractive: It offers instant results always right away. But yeah: going through clipboard can be bad and Send often is quick enough. So be it! 👍

> Another idea would be, to make use of the text to voice function of the translate.googleapis com. Have a look at [this script, which I adapted from teadrinkers](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=63835&p=441969#p441969) in which I have the funtionalty included and gives you an idea how I would like to have it added.

Oh I didn't know abouvt this! Nice! So we'd have another option in the menu which plays back the sound of the translation! Nice 👍 looking forward to that1!

> Sometime looking for a german word (auto -> en) results in the same german word (e.g. “Haus” or “egal”). I know that teadrinkers translate skript will return the same word back, if the search did not find something. But an error message may would the better approach.

hehe yeah! I think I could have some more info from the returned metadata displayed to show what it actually got. Turns out: [Haus](https://translate.google.com/?sl=auto&tl=de&text=Haus&op=translate) is autodetected as english! eehhh it's the [plural of hau](https://www.merriam-webster.com/dictionary/hau) 🤷‍♀️ . For "egal" if get "no matter" back.
But yeah: lets have some feedback on same words returned! 👍

**Comment by Cyberklabauter** [comment]
> Have a look at [this script, which I adapted from teadrinkers](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=63835&p=441969#p441969) in which I have the funtionalty included and gives you an idea how I would like to have it added.

I have posted it at the ahk forum, because the code tag in github somehow messed my code up. Look at the link above. The core is from teadrinker. The little read aloud interface is adapted from garry. I put all together in a little popupmenu, which shows all possible translations, let you pick one and paste the choosen entry (or go to the read aloud function). 

In terms of handle the clipboard, you could try to use the [WinClip Lib](https://www.mediafire.com/folder/7t95clefagt9k/WinClip)  (iCopy and iPaste) to keep the clipboard itself antouched In this version a few bug fixes are incooperate (which you can find around the ahk forum). An alternative may would be [Clip()](https://www.autohotkey.com/boards/viewtopic.php?t=62156) (I have not tested it).

**Comment by ewerybody** [comment]
Ah true! We already HAD **WinClip** in our lib once but it was unused yet and in a rage of cleanup I removed a lot of these.

I still have it in a separate folder and actually have the [WinClipv2 project by FuPeiJiang](https://github.com/FuPeiJiang/WinClipv2) starred already 😅 Should have a deeper look into it! 👍

Thanks for the mediafire file drop but ... is this the latest version? The github one looks a little more recent although this header block is missing. 🤔

**Comment by Cyberklabauter** [comment]
> [WinClipv2 project by FuPeiJiang](https://github.com/FuPeiJiang/WinClipv2)  is a AHK 2 project. I am not sure if it is fully compatible to AHK_L. But my code is based on the code in the [AHK-forum](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=29314&sid=1490accee0fbb2301d2bc74cde64dcd2#p137839) which is referred by FuPeiJiang WinClipv2 project on his github site. 

I fixed only small bugs, like converting bug with UTF8 and the little pause around line 400. Without it you may get an error on slower systems. There are still other encodings done in CP0. Not sure if they will cause problem as well. I did not got some, so I left it as it is. 

The header was added by me.

**Comment by ewerybody** [comment]
Ah okok. I see. I just tried to get my head around the lib and I guess the best thing for now is to replace my crappy code with calls to WinClip but inside of the a2 clipboard lib. So aaall users get the benefits right away and don't need to change a thing. 

This works: Is it how one would use it?

https://github.com/ewerybody/a2/blob/51afc7e717e5831cc72d888c108c483e7b4e1d79/lib/Autohotkey/lib/clipboard.ahk#L11-L15

**Comment by Cyberklabauter** [comment]
Basically yes (If you haven't, have a look at the word file I had sent you. It has the documentation and examples how to use it). 

I wondering if that is the best method to use it. Because your function limits you in the use of WinClip (but it is may the faster way of implementing it). 

I usually used a global object (wc := new WinClip). To use it in a function I made it avaible by "global wc" in the first line within the function. Because the Clipboard and the "second hidden clipboard" (iCopy/iPase) are kind of global, this will give you more flexibility; e.g. if you would like to load local file into the clipboard or if you would like to use the clipboard content in a different avaible format you could use your global object from everythere. In your case you won't have access to anymore.

You may use the 
[try](https://www.autohotkey.com/docs/commands/Try.htm) {
    ...
} [finally](https://www.autohotkey.com/docs/commands/Finally.htm) {
    ...
}

[try](https://www.autohotkey.com/docs/commands/Try.htm) {
    ...
} [catch](https://www.autohotkey.com/docs/commands/Catch.htm) e {
    ...
} [finally](https://www.autohotkey.com/docs/commands/Finally.htm) {
    ...
}

To make sure, that the memory frees even if an exception is thrown.

**Comment by ewerybody** [comment]
Ok nice :) 
Is the word document any different from whats on [the website](https://apathysoftworks.com/ahk/index.html#MainMenu%20WinClip%20%5B%5BWinClip%20examples%5D%5D)?

This seems to get out of the scope of this issue here. Lets move it to the main project here: [**a2#252**](https://github.com/ewerybody/a2/issues/252)

**Comment by ewerybody** [comment]
Ok. I just had a look into the TTS script.. What it all this JS for?! I mean I'm getting a URL with this tk value?! whats that for? seems its also working without can't we just download the file without all this?! 🙄

**Comment by ewerybody** [comment]
Ok this got some overhaul es well :)
![image](https://user-images.githubusercontent.com/218956/154035608-76de3d87-0071-4a30-abe0-bed7f8d8acca.png)

**Comment by Cyberklabauter** [comment]
👍Looks great!
